language: node_js
node_js:
  - "8.15"

notifications:
  email: false

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      sudo: true
      services: docker
      language: generic
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew install git-lfs
    elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get install p7zip-full
    fi

install:
  - nvm install
  - npm i

before_script:
  - git lfs pull

script:
  - |
    if [ "$TRAVIS_BRANCH" == "develop" ]; then
      npm run dist
    elif [ "$TRAVIS_BRANCH" == "master" ]; then
      npm run env
      npm run release
    fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
