image: Visual Studio 2017

configuration: Debug

init:
  - git config --global core.autocrlf input

shallow_clone: true

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8.15
  - npm i --global --production windows-build-tools@4
  - npm i

platform:
  - x64

build_script:
  - npm run dist

test: "off"

for:
-
  branches:
    only:
      - master

  configuration: Release
  build_script:
    - npm run env
    - npm run release
