image: Visual Studio 2017

branches:
  only:
    - master
    - develop

init:
  - git config --global core.autocrlf input

shallow_clone: true

environment:
  DEBUG: electron-builder

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node LTS x64
  - npm i --global --production windows-build-tools
  - yarn

platform:
  - x64

build_script:
  - yarn release

test: off
