name: Auto Tag

on:
  push:
    branches:
      - dev
      - stg

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Auto Tag
      uses: butlerlogic/action-autotag@stable
      if: github.ref != 'refs/heads/main'
      env:
        GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
      with:
        strategy: package
        tag_suffix: "-${{ github.ref_name }}"
