name: Auto Tag

on:
  push:
    branches:
      - dev
      - stg
      - lmn

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: butlerlogic/action-autotag@stable
      env:
        GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
      with:
        strategy: package
        tag_suffix: "-${{ env.GITHUB_REF_NAME }}"